### ISSUE TITLE
Add CONTRIBUTING.md 

### ISSUE THREAD

**Issue by csgeeek** [tamton-aquib/bruttle#1]
Hey @tamton-aquib . Can I add a `CONTRIBUTING.md`  to the repository as part of `hacktoberfest`?

This will be helpful for anyone who's looking forward to contributing to your repository. Please assign this to me.

**Comment by tamton-aquib** [comment]
Heyyo @Yaswanth820, 
> Can I add a CONTRIBUTING.md to the repository as part of hacktoberfest?

Of course, go ahead 😅

**Comment by csgeeek** [comment]
Thanks man, 

Are there any specific things that you want me to include in `CONTRIBUTING.md` ? or should I make a general one?

Also, Can you please add hacktoberfest label for the issue?

**Comment by tamton-aquib** [comment]
> Are there any specific things that you want me to include in CONTRIBUTING.md ? or should I make a general one?

General one would be good, that way i can change it later along the line if needed.

> Also, Can you please add hacktoberfest label for the issue?

Done 👍🏻

**Comment by tamton-aquib** [comment]
Closing the issue as #2 is merged.
